### ISSUE TITLE
Add Redis for Nextcloud

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/server-infra#3]
There should be a Redis instance to improve performance on Nextcloud - this should fix the file locking error. If not, disable file locking.

**Comment by Justintime50** [comment]
Config: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/caching_configuration.html#recommendations-based-on-type-of-deployment

Docker:
```
nextcloud_redis:
  image: redis:5-alpine
  container_name: nextcloud_redis
  expose:
    - 6379
```
